version: '3'
services:
    android:
        build: .
        ports:
        - "8080:80"
        depends_on:
        - mysql
        - node
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
        - ./mysql:/var/lib/mysql
        ports:
        - "3306:3306"
    node:
        image: "node:8"
        user: "node"
        working_dir: /home/node/app
        environment:
        - NODE_ENV=production
        volumes:
        - ./:/home/node/app
        expose:
        - "8081"
        command: "npm start"