version: '3'
services:
	web:
		build: .
		ports:
			- "8080:80"
	mysql:
  		image: mysql:5.7
  		environment:
   			MYSQL_DATABASE: ${DB_DATABASE}
   			MYSQL_USER: ${DB_USERNAME}
   			MYSQL_PASSWORD: ${DB_PASSWORD}
  		volumes:
    			- ./mysql:/var/lib/mysql
  		ports:
   			- "3306:3306"
